# Generated by Django 4.1 on 2023-10-15 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_invoice_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='date_time',
            new_name='date',
        ),
    ]
